spring.application.name=bff-agendador

# Feign
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000
spring.cloud.openfeign.client.config.default.logger-level=basic


# ? Habilitar Apache HttpClient (suporta PATCH)
spring.cloud.openfeign.httpclient.hc5.enabled=true

# URLs dos microsserviços
usuario.url=${USUARIO_SERVICE_URL:http://localhost:8080}
agendador-tarefas.url=${TAREFAS_SERVICE_URL:http://localhost:8081}
notificacao.url=${NOTIFICACAO_SERVICE_URL:http://localhost:8082}

# Server
server.port=8083

# Usuário de sistema para o cron
sistema.usuario.email=${SISTEMA_EMAIL:admin@admin.com}
sistema.usuario.senha=${SISTEMA_SENHA:1234}

# Cron (a cada 5 minutos)
cron.horario=${CRON_NOTIFICACAO:0 0/5 * * * ?}

# Logging
logging.level.com.javanauta.bffagendador=INFO
logging.level.feign=INFO

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html